name: workflow
on:
  push:
    branches:
      - main
jobs:
  test:
      name: Test app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - run: sh ./run_test.sh
        - uses: actions/upload-artifact@v2
          with:
            name: Test Results
            path: ${{ steps.test.outputs.combined_results_path }}